export interface ServiceWorkerOptions {
  /** Prefix for this app's cache names, e.g. "myapp" -> "myapp-shell-v1", "myapp-api-v1". */
  cachePrefix: string;
  /** Path prefix that identifies API requests. Default "/api/". */
  apiPrefix?: string;
  /** Path prefixes that must never be cached (sensitive or large). Default auth + files. */
  skipPaths?: string[];
  /** Page served when a navigation fails offline and nothing is cached. Default "/". */
  navigationFallback?: string;
}

/**
 * Build the source of a secure, network-first service worker as a string. Write the result to a
 * static file your site serves at the root (e.g. `public/sw.js`), then call
 * `registerServiceWorker()` from your app.
 *
 * Strategy: app shell cache-first; navigations network-first with an offline page fallback; API
 * GETs network-first (fresh online, cached only as an offline fallback). Never caches the skip
 * paths, only same-origin 200s, and clears the API cache when the app posts "clear-api-cache".
 */
export function generateServiceWorker(opts: ServiceWorkerOptions): string {
  const {
    cachePrefix,
    apiPrefix = "/api/",
    skipPaths = ["/api/auth/", "/api/files/"],
    navigationFallback = "/",
  } = opts;

  if (!cachePrefix) throw new Error("generateServiceWorker: cachePrefix is required");

  const skips = JSON.stringify(skipPaths);

  return `// Generated by @baryodev/pwa-kit — do not edit by hand; regenerate instead.
const SHELL = ${JSON.stringify(cachePrefix + "-shell-v1")};
const API = ${JSON.stringify(cachePrefix + "-api-v1")};
const API_PREFIX = ${JSON.stringify(apiPrefix)};
const SKIP = ${skips};
const NAV_FALLBACK = ${JSON.stringify(navigationFallback)};

self.addEventListener("install", () => self.skipWaiting());

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== SHELL && k !== API).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("message", (event) => {
  if (event.data === "clear-api-cache") event.waitUntil(caches.delete(API));
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (SKIP.some((p) => url.pathname.startsWith(p))) return;

  if (url.pathname.startsWith(API_PREFIX)) {
    event.respondWith(
      fetch(req)
        .then((resp) => {
          if (resp.ok && resp.type === "basic") {
            const copy = resp.clone();
            caches.open(API).then((c) => c.put(req, copy));
          }
          return resp;
        })
        .catch(() =>
          caches.match(req).then(
            (cached) =>
              cached ||
              new Response(JSON.stringify({ offline: true }), {
                status: 503,
                headers: { "Content-Type": "application/json" },
              }),
          ),
        ),
    );
    return;
  }

  if (req.mode === "navigate") {
    event.respondWith(
      fetch(req)
        .then((resp) => {
          const copy = resp.clone();
          caches.open(SHELL).then((c) => c.put(req, copy));
          return resp;
        })
        .catch(() => caches.match(req).then((r) => r || caches.match(NAV_FALLBACK))),
    );
    return;
  }

  event.respondWith(
    caches.match(req).then(
      (cached) =>
        cached ||
        fetch(req).then((resp) => {
          if (resp.ok && resp.type === "basic") {
            const copy = resp.clone();
            caches.open(SHELL).then((c) => c.put(req, copy));
          }
          return resp;
        }),
    ),
  );
});
`;
}
